### ISSUE TITLE
Profiling Dask implementation

### ISSUE THREAD

**Issue by mrocklin** [StanfordLegion/task-bench#41]
I took at look at the dask/task_bench_direct.py file to see if it was operating near maximum efficiency.  I *think* I found a couple things that might help.  

First, I set things up to run asynchronously, so that I could run the cProfile module to see what was taking time.  I found that it was spending about half of its time serializing functions.  I inserted a `breakpoint()` call near where you define a task and tried pickling your function and found that it couldn't be pickled (Python's default serialization for Python objects).  This was because it was defined in the `__main__` namespace rather than imported from a module (imported functions are much easier to specify than dynamically created ones).  Dask can still move these, but it uses a more complex system to serialize them, which is expensive.  So I moved the execution code over to a separate file so that we imported these functions from another file, so that Python would identify them as a module.

*Side note: I don't envy you trying to do a benchmark across projects that span multiple languages.  It's near impossible to get anywhere near optimal performance without understanding the intricacies of systems like Python.*

After doing that I also changed these lines:

```diff
+        from dask.distributed import wait
+        futures = client.get(computations, results, sync=False)
+        wait(futures)
-        client.get(computations, results)
```

Previously this code block ran all of the computations and then pulled them all back to the scheduler, and then from there to the client.  For larger numbers of tasks (I was playng with 160k) collecting all of the tasks at once is somewhat awkward.  I'm not sure if you wanted to benchmark bringing everything to one node, but I assumed not.  Now we just ask the workers to run the tasks and then wait for them to complete.  This would become more and more of a bottleneck for larger numbers of tasks.

I get something like 1500 tasks per second on my personal laptop, running both the client and scheduler in the same process (I would expect slightly better performance separating these two).  As a rule of thumb if you're not getting somewhere between 1000-5000 tasks per second with Dask then something is probably wrong.

### Couldn't use separate processes

I think related to my issues in #40 I wasn't able to successfully run a dask-worker process on my system, so I ended up ripping out CLI argument handling and defining a cluster locally in Python. My apologies, this probably makes it marginally harder to integrate these changes.

**Comment by mrocklin** [comment]
My local "run everything in a single thread" code is here: https://github.com/StanfordLegion/task-bench/compare/master...mrocklin:dask-play

It's not useful for benchmarking on larger systems, but shows separating the execution to a separate file and also swapping out `get` for `wait` and `get`.  It uses async programming, which you shouldn't have to copy over (though is fun and useful to learn about, should you find yourself with some time).

**Comment by elliottslaughter** [comment]
Thanks for the suggestions. I'd learned about cloudpickle because it couldn't handle the CFFI handles---but I hadn't considered the performance implications at the time.

This should be fixed by c47f870f02c82b83bdc4f44df2f5960a67b15e16 and e844eae9a53a92428c18953624ed64ed2a686e67. I'll rerun the results and see how the performance changes.

**Comment by mrocklin** [comment]
I didn't see a huge impact locally.  But I wouldn't be surprised if this
becomes a bigger deal on larger systems.  The `get` bit in particular.

**Comment by elliottslaughter** [comment]
I'm seeing a pretty substantial improvement on the more complicated patterns (e.g. up to 6x better on spread at 8 nodes). Thanks for the suggestions, and let me know if think of anything else I should do (either here or in a new issue).

Closing this for now.

**Comment by mrocklin** [comment]
I'm very glad to hear it!  I'm curious, do you see other situations where the tasks-per-second drops below 1000?  If so then there are likely other issues going on.

**Comment by elliottslaughter** [comment]
I'm still seeing a dropoff in TPS with higher number of dependencies:

| Dependencies per Task | TPS     | 
|-----------------------|---------| 
| 0                     | 4014.82 | 
| 1                     | 1483.37 | 
| 2                     | 1549.94 | 
| 3                     | 1549.94 | 
| 4                     | 1112.86 | 
| 5                     | 980.06  | 
| 6                     | 863.45  | 
| 7                     | 800.3   | 
| 8                     | 712.94  | 
| 9                     | 682.35  | 

I don't know if that matches your expectations or not.

Also, there is a slight drop-off with more complicated patterns (e.g. 5 spread out dependencies gets about 800 TPS, rather than 1000 TPS with 5 nearest dependencies).

However, TPS seems to be pretty stable with node count, so we're not losing performance there (at least through 16 nodes or so).

**Comment by elliottslaughter** [comment]
Just to be clear: the numbers above use the smallest possible tasks to maximize TPS (which is the usual way people talk about TPS). This is not the same as what is reported in the paper (where the tasks are constrained so that they hit exactly 50% of peak FLOPS).
